### ISSUE TITLE
Discord crash scrolling through plugin-links channel in the powercord discord

### ISSUE THREAD

**Issue by SamboyCoding** [LandenStephenss/PowercordPluginDownloader#1]
TypeError: Cannot read property 'match' of undefined
    at DownloadButton.render (...\Powercord\plugins\PowercordPluginDownloader\Components\DownloadButton.jsx:17)

Hard crashes discord to this screen.

![image](https://user-images.githubusercontent.com/7011721/87777942-52b10e80-c822-11ea-9ccc-7a5382e071f2.png)

The console.log for GithubLink on line 16 is logging `undefined`, so you presumably just need to check that :)

Thanks for the plugin, it's useful.

**Comment by LandenStephenss** [comment]
Fixed
