### ISSUE TITLE
Connect to Github

### ISSUE THREAD

**Issue by DerMylo** [LandenStephenss/PowercordPluginDownloader#13]
![Unbenannt](https://user-images.githubusercontent.com/90861178/135146714-d0c97206-d34a-456b-8e8c-511dc8dac601.PNG)

I tried tu use the plugin and hit the install plugin box. Then a window showed up where i should connect my githubacount. I did it and as i tried again the same window showed up again

**Comment by xaiyadev** [comment]
Note Detail? Where was the Button. What Plugin did you Install (or maybe say that you installed **this** Plugin) And so on. This can mean anything. Did you try to Log in so And so on

**Comment by Loremly** [comment]
This means the repository is private (most likely reason) and cannot be cloned/downloaded
