### ISSUE TITLE
Not Downloading Plugins

### ISSUE THREAD

**Issue by MaybeEtienne** [LandenStephenss/PowercordPluginDownloader#15]
When I hit the Download Plugin button nothing Happens, the Plugin did not download. (Im on Windows)

https://user-images.githubusercontent.com/91177350/138559978-9ee8fb00-b700-4f4a-b157-dff0f328cd19.mp4

**Comment by xaiyadev** [comment]
Maybe try the beta better looking card feature in the settings and download it

**Comment by MaybeEtienne** [comment]
> Maybe try the beta better looking card feature in the settings and download it

I already did that it shows the Message "This plugin is already installed" even though it isn't.. It's still not downloading.

**Comment by xaiyadev** [comment]
Try to Reinstall the plugin. Maybe it has a new Version,

And If this doesnt Work try reinstalling powercord. It can bei that the plugin folder is corupted,

Do you maybe have any logs?

**Comment by LandenStephenss** [comment]
@MaybeEtienne sorry just now getting to this!

Do you happen to have git installed? Assuming you do there should be no issues, and whenever a plugin is finished being installed it should show "plugin has been installed" or "plugin is already installed" or something similar to those two

**Comment by LandenStephenss** [comment]
Closed with no response
