### ISSUE TITLE
No longer shows up in linkContextMenu

### ISSUE THREAD

**Issue by SheepCommander** [LandenStephenss/PowercordPluginDownloader#16]
![image](https://user-images.githubusercontent.com/66646514/148682951-2d619c3c-b016-4a55-be5d-225986472170.png)

**Comment by LandenStephenss** [comment]
Yeah i know, figuring out a fix at some point but some point is not today.

**Comment by SheepCommander** [comment]
aight lol, but yeah it still works (except for the ones that have a github link before the actual repo, mainly the "closes suggestion <>")

**Comment by 0xCUB3** [comment]
Any fix yet? This is still happening :(
