### ISSUE TITLE
Merge with Theme Downloader?

### ISSUE THREAD

**Issue by DracoClaw** [LandenStephenss/PowercordPluginDownloader#19]
It seems silly to have two plugins that do the exact same thing. I'm sure anyone who uses one would also use the other, so why not have them in one place.

**Comment by LandenStephenss** [comment]
It is silly, and it's been thought about but i've just never really had the time to do it (until now). But this brings up an issue about context menus again, either leave them out entirely or find a way to sift through the github repo without using a absolute shit ton of data or bandwidth and be able to tell what kind of repo it is (plugin or theme). Although i do have a working version where it is both plugins in one.
