### ISSUE TITLE
Shows the hover effect on both buttons if both shown

### ISSUE THREAD

**Issue by Captain8771** [LandenStephenss/PowercordPluginDownloader#22]
So if a repo has both a manifest.json and powercord_manifest.json, plugindownloader shows both download plugin and download theme

now normally this would be okay, ***however***, when hovering over one, the both light up

repo to test with: `https://github.com/CreArts-Community/Mention-Links`

preview: ![image](https://media.discordapp.net/attachments/856948115729809433/953736248835600534/unknown.png)

**Comment by LandenStephenss** [comment]
Blame vizality, no way to fix this as there is no difference in vizality manifest and powercord_manifest, other than just not showing any button at all.
