### ISSUE TITLE
Install plugin from search menu

### ISSUE THREAD

**Issue by Titaniumtown** [LandenStephenss/PowercordPluginDownloader#5]
Can you make it so when I search for a plugin on the powercord discord, i don't have to click "jump" the right click on the link? I would just like to right click on the link in the results area.

**Comment by LandenStephenss** [comment]
Sorry for the late response.
I am not sure if i will implement this or if i will even be able to. But i will probably look into it.

**Comment by Titaniumtown** [comment]
ok!

**Comment by LandenStephenss** [comment]
yeah totally forgot that this was a thing until i seen a random issue. Not sure if you even still care. But in the next week or two i'm gonna add something to check if the repo is a powercord plugin or not. I'll probably try to add it then. Although if i'm not wrong im just injecting into urls and checking for git. So it should already work if you right click a url in search? but im not sure

**Comment by Olebeh** [comment]
Yeah, and this is still a thing

**Comment by MulverineX** [comment]
bump. with the new system you have you can reuse the [injector I use](https://github.com/AAGaming00/rich-quotes/blob/master/index.js#L72)

**Comment by LandenStephenss** [comment]
@MulverineX if you want you can make a PR adding it, i'd do it myself but i'm tired.
